Feature/mobilome into gff script
EBI-Metagenomics/mettannotator pull request #16
Opened 2024-03-13 10:29 UTC by tgurbich

Added a script that adds lines from a merged mobilome GFF into the main annotation GFF.

2024-03-13 12:35 UTC, Ales-ibt requested changes
Thank you for this. I checked the output and it looks quite clean and informative. I found just a couple of details I have addressed in the code.

2024-03-14 13:01 UTC, tgurbich commented on postprocessing/add_mobilome_to_gff.py
> +                )
Thanks! added

2024-03-14 13:01 UTC, tgurbich commented on postprocessing/add_mobilome_to_gff.py
> +                feature = "nested_mobile_genetic_element"
Done

2024-03-14 13:29 UTC, Ales-ibt approved these changes

2024-03-14 13:29 UTC, merged